# Generated by Django 4.2 on 2024-07-18 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0069_alter_userprofile_is_frequency_pic_dir'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venue',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='question',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
