# Generated by Django 4.2 on 2024-07-18 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0071_delete_square'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beacon',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
        migrations.RemoveField(
            model_name='myclubuser',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='myplayer',
            name='environment',
        ),
        migrations.RemoveField(
            model_name='userprofile2',
            name='user',
        ),
        migrations.DeleteModel(
            name='Environment',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='MyClubUser',
        ),
        migrations.DeleteModel(
            name='MyPlayer',
        ),
        migrations.DeleteModel(
            name='UserProfile2',
        ),
    ]
