# Generated by Django 4.2 on 2024-07-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0072_delete_beacon_remove_event_attendees_delete_listitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=-1, verbose_name='size')),
            ],
        ),
    ]
