# Generated by Django 4.2 on 2024-07-18 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0073_listitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pending_xpos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pending_ypos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_label_holder',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_question_area_holder',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_question_area_strength_holder',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='temp_question_holder',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wrong_answers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='x',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='xpos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='y',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='ypos',
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='nick',
            field=models.CharField(default='-', max_length=120, verbose_name='nick'),
        ),
    ]
