# Generated by Django 4.2 on 2024-07-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0074_remove_userprofile_correct_answers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomeentry',
            name='footprints',
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='footprints',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.footprint'),
        ),
    ]
