# Generated by Django 4.2 on 2024-07-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0075_remove_genomeentry_footprints_genomeentry_footprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomeentry',
            name='footprints',
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='footprints',
            field=models.ManyToManyField(blank=True, to='event.footprint'),
        ),
    ]
