# Generated by Django 4.2 on 2024-07-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0076_remove_genomeentry_footprints_genomeentry_footprints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genomeentry',
            name='footprint_size',
        ),
        migrations.AddField(
            model_name='genomeentry',
            name='footprint_perc',
            field=models.FloatField(default=-1.0, verbose_name='footprint_size'),
        ),
    ]
