# Generated by Django 4.2 on 2024-07-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0078_genomeentry_footprint_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCBIentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('link', models.CharField(max_length=120, verbose_name='name')),
            ],
        ),
    ]
