# Generated by Django 4.2 on 2024-07-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0079_ncbientry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncbientry',
            name='link',
            field=models.CharField(max_length=120, verbose_name='link'),
        ),
    ]
