# Generated by Django 4.2 on 2024-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0080_alter_ncbientry_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListItem2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.BooleanField(default=False)),
                ('size', models.IntegerField(default=-1, verbose_name='size')),
            ],
        ),
    ]
