# Generated by Django 4.2 on 2024-07-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0081_listitem2'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCBISubentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('link', models.CharField(max_length=120, verbose_name='link')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subentries', to='event.ncbientry')),
            ],
        ),
    ]
