# Generated by Django 4.2 on 2024-07-22 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0083_remove_ncbisubentry_entry_ncbientry_subentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncbientry',
            name='link',
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='asm_name',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='asm_name'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='assembly_accession',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='assembly_accession'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='assembly_level',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='assembly_level'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='assembly_type',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='assembly_type'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='contig_count',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='contig_count'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='ftp_path',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='ftp_path'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='gbrs_paired_asm',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='gbrs_paired_asm'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='gc_percent',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='gc_percent'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='genome_rep',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='genome_rep'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='genome_size',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='genome_size'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='genome_size_ungapped',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='genome_size_ungapped'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='organism_name',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='organism_name'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='replicon_count',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='replicon_count'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='scaffold_count',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='scaffold_count'),
        ),
    ]
