# Generated by Django 4.2 on 2024-07-22 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0084_remove_ncbientry_link_ncbientry_asm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbientry',
            name='link',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='link'),
        ),
    ]
