# Generated by Django 4.2 on 2024-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0085_ncbientry_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbientry',
            name='has_representative',
            field=models.CharField(blank=True, default='-1', max_length=120, verbose_name='has_reprsentative'),
        ),
    ]
