# Generated by Django 4.2 on 2024-07-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0087_ncbientry_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbientry',
            name='seq_rel_date',
            field=models.CharField(default='-1', max_length=120, verbose_name='database'),
        ),
    ]
