# Generated by Django 4.2 on 2024-07-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0088_ncbientry_seq_rel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncbientry',
            name='annotation_date',
            field=models.CharField(default='-1', max_length=120, verbose_name='annotation_date'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='annotation_name',
            field=models.CharField(default='-1', max_length=120, verbose_name='annotation_name'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='annotation_provider',
            field=models.CharField(default='-1', max_length=120, verbose_name='annotation_provider'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='asm_not_live_date',
            field=models.CharField(default='-1', max_length=120, verbose_name='asm_not_live_date'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='asm_submitter',
            field=models.CharField(default='-1', max_length=120, verbose_name='asm_submitter'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='bioproject',
            field=models.CharField(default='-1', max_length=120, verbose_name='bioproject'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='biosample',
            field=models.CharField(default='-1', max_length=120, verbose_name='biosample'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='excluded_from_refseq',
            field=models.CharField(default='-1', max_length=120, verbose_name='excluded_from_refseq'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='group',
            field=models.CharField(default='-1', max_length=120, verbose_name='group'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='infraspecific_name',
            field=models.CharField(default='-1', max_length=120, verbose_name='infraspecific_name'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='isolate',
            field=models.CharField(default='-1', max_length=120, verbose_name='isolate'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='non_coding_gene_count',
            field=models.CharField(default='-1', max_length=120, verbose_name='non_coding_gene_count'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='paired_asm_comp',
            field=models.CharField(default='-1', max_length=120, verbose_name='paired_asm_comp'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='protein_coding_gene_count',
            field=models.CharField(default='-1', max_length=120, verbose_name='protein_coding_gene_count'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='pubmed_id',
            field=models.CharField(default='-1', max_length=120, verbose_name='pubmed_id'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='refseq_category',
            field=models.CharField(default='-1', max_length=120, verbose_name='refseq_category'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='relation_to_type_material',
            field=models.CharField(default='-1', max_length=120, verbose_name='relation_to_type_material'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='release_type',
            field=models.CharField(default='-1', max_length=120, verbose_name='release_type'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='species_taxid',
            field=models.CharField(default='-1', max_length=120, verbose_name='species_taxid'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='taxid',
            field=models.CharField(default='-1', max_length=120, verbose_name='taxid'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='total_gene_count',
            field=models.CharField(default='-1', max_length=120, verbose_name='total_gene_count'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='version_status',
            field=models.CharField(default='-1', max_length=120, verbose_name='version_status'),
        ),
        migrations.AddField(
            model_name='ncbientry',
            name='wgs_master',
            field=models.CharField(default='-1', max_length=120, verbose_name='wgs_master'),
        ),
        migrations.AlterField(
            model_name='ncbientry',
            name='gbrs_paired_asm',
            field=models.CharField(default='-1', max_length=120, verbose_name='gbrs_paired_asm'),
        ),
        migrations.AlterField(
            model_name='ncbientry',
            name='genome_size_ungapped',
            field=models.CharField(default='-1', max_length=120, verbose_name='genome_size_ungapped'),
        ),
        migrations.AlterField(
            model_name='ncbientry',
            name='seq_rel_date',
            field=models.CharField(default='-1', max_length=120, verbose_name='seq_rel_date'),
        ),
    ]
