# Generated by Django 4.2 on 2024-08-06 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0089_ncbientry_annotation_date_ncbientry_annotation_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='analysed_gb_files_dir',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='final_results_dir',
            field=models.CharField(default='D:/final_results/', max_length=120, verbose_name='analysed_gb_files'),
        ),
    ]
